# -*- coding: utf-8 -*-
"""Home Energy Savings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FN0HSfL7CwiH2T5oEp2RcZTlQWdcbQ3
"""

# HOME ENERGY SAVING ADVISOR

# 1. INSTALL REQUIREMENTS
!pip install flask pyngrok

# 2. DATABASE SETUP
import sqlite3

def init_database():
    """Initialize the SQLite database with energy-saving rules"""
    conn = sqlite3.connect('energy_rules.db')
    cursor = conn.cursor()

    # Create rules table (without inline comments)
    cursor.execute('''CREATE TABLE IF NOT EXISTS rules (
        id INTEGER PRIMARY KEY,
        conditions TEXT NOT NULL,
        actions TEXT NOT NULL
    )''')

    # Clear existing data to prevent duplicates
    cursor.execute("DELETE FROM rules")

    # Energy-saving rules
    energy_rules = [
        # ELECTRICITY
        ("high_electricity_bill", "Unplug devices when not in use, Use smart power strips"),
        ("high_electricity_bill,daytime_usage", "Shift energy-intensive tasks to off-peak hours"),

        # LIGHTING
        ("poor_lighting", "Replace all bulbs with LED lighting"),
        ("poor_lighting,outdoor_lighting", "Install motion-sensor outdoor lights"),

        # HEATING/COOLING
        ("high_heating_costs", "Set thermostat to 68°F (20°C) in winter"),
        ("drafty_windows", "Apply weatherstripping, Install thermal curtains"),

        # WATER
        ("high_water_heating_costs", "Lower water heater to 120°F (49°C)"),
        ("leaky_faucets", "Repair dripping faucets immediately"),

        # APPLIANCES
        ("old_appliances", "Upgrade to ENERGY STAR certified appliances"),

        # COMBINATION RULES
        ("high_electricity_bill,summer", "Install ceiling fans (allows 4°F higher AC setting)"),
        ("drafty_windows,old_house", "Consider window replacement with double-pane glass")
    ]

    cursor.executemany("INSERT INTO rules (conditions, actions) VALUES (?, ?)", energy_rules)
    conn.commit()
    conn.close()
    print("✅ Database initialized with expert rules")

# 3. FLASK APPLICATION

from flask import Flask, render_template_string, request
from pyngrok import ngrok

app = Flask(__name__)

# 3.1 Homepage

@app.route('/')
def home():
    """Render the main input form with energy issue categories"""
    return render_template_string('''
    <!DOCTYPE html>
    <html>
    <head>
        <title>Home Energy Saving Advisor</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            :root {
                --primary: #2E86AB;
                --secondary: #F18F01;
                --light: #F7F7FF;
                --dark: #2D3047;
            }
            body {
                font-family: 'Segoe UI', system-ui, sans-serif;
                line-height: 1.6;
                color: var(--dark);
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f9fa;
            }
            header {
                text-align: center;
                margin-bottom: 30px;
                padding: 20px;
                background: var(--primary);
                color: white;
                border-radius: 8px;
                box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            }
            h1 {
                margin: 0;
                font-size: 2.2em;
                font-weight: 600;
            }
            .category {
                background: white;
                padding: 20px;
                margin-bottom: 20px;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.05);
            }
            .category h2 {
                color: var(--primary);
                margin-top: 0;
                border-bottom: 2px solid var(--secondary);
                padding-bottom: 8px;
            }
            .checkbox-group {
                margin: 15px 0;
            }
            .checkbox-label {
                display: block;
                position: relative;
                padding-left: 35px;
                margin-bottom: 12px;
                cursor: pointer;
                user-select: none;
            }
            .checkbox-label input {
                position: absolute;
                opacity: 0;
                cursor: pointer;
                height: 0;
                width: 0;
            }
            .checkmark {
                position: absolute;
                top: 0;
                left: 0;
                height: 22px;
                width: 22px;
                background-color: #eee;
                border-radius: 4px;
            }
            .checkbox-label:hover input ~ .checkmark {
                background-color: #ddd;
            }
            .checkbox-label input:checked ~ .checkmark {
                background-color: var(--primary);
            }
            .checkmark:after {
                content: "";
                position: absolute;
                display: none;
            }
            .checkbox-label input:checked ~ .checkmark:after {
                display: block;
            }
            .checkbox-label .checkmark:after {
                left: 7px;
                top: 3px;
                width: 6px;
                height: 12px;
                border: solid white;
                border-width: 0 3px 3px 0;
                transform: rotate(45deg);
            }
            .submit-btn {
                background-color: var(--primary);
                color: white;
                border: none;
                padding: 14px 20px;
                font-size: 16px;
                border-radius: 6px;
                cursor: pointer;
                width: 100%;
                font-weight: 600;
                transition: background-color 0.3s;
            }
            .submit-btn:hover {
                background-color: #1a6a8a;
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Home Energy Saving</h1>
            <p>Get personalized recommendations to reduce your energy consumption</p>
        </header>

        <form action="/recommend" method="post">
            <div class="category">
                <h2>Electricity Usage</h2>
                <div class="checkbox-group">
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="high_electricity_bill">
                        <span class="checkmark"></span> High electricity bill
                    </label>
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="daytime_usage">
                        <span class="checkmark"></span> Heavy daytime usage
                    </label>
                </div>
            </div>

            <div class="category">
                <h2>Lighting</h2>
                <div class="checkbox-group">
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="poor_lighting">
                        <span class="checkmark"></span> Poor lighting efficiency
                    </label>
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="outdoor_lighting">
                        <span class="checkmark"></span> Outdoor lighting left on
                    </label>
                </div>
            </div>

            <div class="category">
                <h2>Heating & Cooling</h2>
                <div class="checkbox-group">
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="high_heating_costs">
                        <span class="checkmark"></span> High heating costs
                    </label>
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="drafty_windows">
                        <span class="checkmark"></span> Drafty windows/doors
                    </label>
                </div>
            </div>

            <div class="category">
                <h2>Water Heating</h2>
                <div class="checkbox-group">
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="high_water_heating_costs">
                        <span class="checkmark"></span> High water heating costs
                    </label>
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="leaky_faucets">
                        <span class="checkmark"></span> Leaky faucets/pipes
                    </label>
                </div>
            </div>

            <div class="category">
                <h2>Appliances</h2>
                <div class="checkbox-group">
                    <label class="checkbox-label">
                        <input type="checkbox" name="conditions" value="old_appliances">
                        <span class="checkmark"></span> Old appliances (>10 years)
                    </label>
                </div>
            </div>

            <button type="submit" class="submit-btn">Get Energy-Saving Recommendations</button>
        </form>
    </body>
    </html>
    ''')

# 3.2 Recommendations Page

@app.route('/recommend', methods=['POST'])
def recommend():
    """Process user input and display personalized recommendations"""
    user_conditions = request.form.getlist('conditions')
    conn = sqlite3.connect('energy_rules.db')
    cursor = conn.cursor()

    # Get matching rules from database
    recommendations = set()
    for rule in cursor.execute("SELECT conditions, actions FROM rules"):
        rule_conditions = rule[0].split(',')
        if all(cond in user_conditions for cond in rule_conditions):
            for action in rule[1].split(", "):
                recommendations.add(action.strip())

    conn.close()

    # Sort recommendations alphabetically
    sorted_recommendations = sorted(list(recommendations))

    return render_template_string('''
    <!DOCTYPE html>
    <html>
    <head>
        <title>Your Energy-Saving Recommendations</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            :root {
                --primary: #2E86AB;
                --secondary: #F18F01;
                --light: #F7F7FF;
                --dark: #2D3047;
            }
            body {
                font-family: 'Segoe UI', system-ui, sans-serif;
                line-height: 1.6;
                color: var(--dark);
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background-color: #f5f9fa;
            }
            header {
                text-align: center;
                margin-bottom: 30px;
            }
            h1 {
                color: var(--primary);
                margin-bottom: 10px;
            }
            .rec-card {
                background: white;
                padding: 20px;
                margin-bottom: 15px;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.05);
                border-left: 4px solid var(--secondary);
                transition: transform 0.2s;
            }
            .rec-card:hover {
                transform: translateY(-2px);
            }
            .back-btn {
                display: inline-block;
                margin-top: 30px;
                padding: 12px 25px;
                background-color: var(--primary);
                color: white;
                text-decoration: none;
                border-radius: 6px;
                font-weight: 500;
                transition: background-color 0.3s;
            }
            .back-btn:hover {
                background-color: #1a6a8a;
            }
            .empty-state {
                text-align: center;
                padding: 40px;
                background: white;
                border-radius: 8px;
                box-shadow: 0 2px 4px rgba(0,0,0,0.05);
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Your Personalized Recommendations</h1>
            <p>Based on your home's energy profile</p>
        </header>

        {% if recommendations %}
            {% for rec in recommendations %}
            <div class="rec-card">
                {{ rec }}
            </div>
            {% endfor %}
        {% else %}
            <div class="empty-state">
                <h3>No specific recommendations found</h3>
                <p>Try selecting more energy issues for personalized advice</p>
            </div>
        {% endif %}

        <center>
            <a href="/" class="back-btn">Start New Analysis</a>
        </center>
    </body>
    </html>
    ''', recommendations=sorted_recommendations)

# 4. APPLICATION LAUNCH

if __name__ == '__main__':
    # Initialize the database
    init_database()

    # Set up the ngrok tunnel
    try:
        public_url = ngrok.connect(5000).public_url
        print(f"\n✅ YOUR HOME ENERGY SAVING ADVISOR IS READY AT: {public_url}\n")

    except Exception as e:
        print("\n⚠️ FIRST RUN REQUIREMENT:")
        print("1. Get a free auth token from: https://dashboard.ngrok.com/get-started")
        print("2. Run this in a NEW Code cell:")
        print("   !ngrok authtoken YOUR_TOKEN_HERE")
        print("3. Restart the original code cell\n")

    # Launching Flask app
    app.run()